services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    environment:
      FREECURRENCY_API_KEY: ${FREECURRENCY_API_KEY}
      ASPNETCORE_URLS: http://0.0.0.0:${SERVER_PORT}   
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${SERVER_PORT}/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
    env_file: .env
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "${CLIENT_PORT}:80"        
    depends_on:
      server:
        condition: service_healthy
